---
- hosts: flask_node
  become: yes
  vars:
    APP_NAME: CeneoScrapper
    REPOSITORY_URL: https://github.com/kingaborycka/CeneoScraper.git
  tasks:
    - name: "install os packages"
      yum:
        name: python3, python3-pip, git
    - name: "sync repo"
      git:
        repo: "{{REPOSITORY_URL}}"
        dest: "/opt/{{APP_NAME}}"
    - name: "create user"
      user:
        name: "{{APP_NAME}}"
    - name: "create venv"
      pip:
        virtualenv_command: python3 -m venv
        requirements: "/opt/{{APP_NAME}}/requirements.txt"
        virtualenv: "/opt/{{APP_NAME}}/.venv"
    - name: "put systemd cfg"
      template:
        src: files/flask/app.service
        dest: "/etc/systemd/system/{{APP_NAME}}.service"
    - name: "start service"
      systemd:
        daemon_reload: yes 
        name: "{{APP_NAME}}"
        state: restarted
- hosts: load_balancer
  become: yes
  vars:
    app_ips:
      - 172.31.2.56:80
      - 172.31.13.168:80
  tasks:
    - name: install epel
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: install nginx
      yum:
        name: nginx
        state: present
    - name: put nginx conf
      template:
        src: files/lb.conf
        dest: /etc/nginx/conf.d/blog.conf
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded


  